GET http://localhost:5000/courses

###

GET http://localhost:5000/courses/60ca42ef223ed21d0ceb3d57

###

POST http://localhost:5000/courses
Content-Type: application/json

{
    "name": "farmcommand guide"
}

###

DELETE http://localhost:5000/courses/60b7aa65cdc61c14386cf759


###
PUT http://localhost:5000/courses/60ca42ef223ed21d0ceb3d57

Content-Type: application/json

{

    "name": "farmcommand tool"
}

###

DELETE http://localhost:5000/courses/60ca42ef223ed21d0ceb3d57
